name: Pull Request Lint
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  pull-request-lint:
    name: Lint pull request
    runs-on: ubuntu-latest
    steps:
      - name: Lint pull request
        uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
